---
framework: jest
preRun:
  command:
    - yarn install
preMerge:
  env:
    NODE_ENV: test
  pattern:
    - src/container/__tests__/FluxContainer-test.js
postMerge:
  env:
    NODE_ENV: test
  pattern:
    - src/container/__tests__/FluxContainer-test.js
postRun:
  command:
    - yarn --version
version: 1.0
